### ISSUE TITLE
failed to import on arm64

### ISSUE THREAD

**Issue by chopin1998** [letmaik/pyvirtualcam#107]
- Operating system: armbin jammy
- Python version: 3.10.6
- pyvirtualcam version: git/master

git clone the latest code,

python3 setup.py build/ install seems fine,

but when i import the module, it show:

**ImportError: /usr/local/lib/python3.10/dist-packages/pyvirtualcam-0.10.2-py3.10-linux-aarch64.egg/pyvirtualcam/_native_linux_v4l2loopback.cpython-310-aarch64-linux-gnu.so: undefined symbol: CanonicalFourCC
**

**Comment by letmaik** [comment]
I have a feeling this is because you don't clone the submodules of the repo and it still was happily compiling with missing symbols. Can you try `git submodule update --init` and then build/install again? It that works I'll change the setup such that it complains early if the submodule is not cloned.

**Comment by chopin1998** [comment]
> I have a feeling this is because you don't clone the submodules of the repo and it still was happily compiling with missing symbols. Can you try `git submodule update --init` and then build/install again? It that works I'll change the setup such that it complains early if the submodule is not cloned.

ic.... i use apt version libuvc-dev before.

now it canbe imported as expected after _git submodule update_

Thank thee very much!
