### ISSUE TITLE
Using Webcamoid virtual camera

### ISSUE THREAD

**Issue by Ajju2211** [letmaik/pyvirtualcam#71]
I have seen this https://github.com/webcamoid/akvirtualcamera, it supports windows, mac,linux.
I think pyvirtualcam can made as platform independent setup by using  webcamoid  builds.

**Comment by Ajju2211** [comment]
Your project is great for linux because it requires  v4l2loopback only, But in case of windows it requires unity or obs which are the big giant softwares.So I just wanted to point out that you can use the webcamoid builds and ship it along with the pyvirtualcam.
I understand the build requires admin permissions, may be it can taken permission from the user during installation steps, but it might reduce the extra installation of giant obs or unity.

Let's say I wanted to build a desktop application using python and I have used your library in that.But I can not ask the end user to install unity or obs for that right.

**Comment by letmaik** [comment]
See also https://github.com/letmaik/pyvirtualcam/discussions/50#discussioncomment-564551. I'm afraid this is something you will have to deal with in the installer of your application. It's not the job of a library, given all the constraints. Have a look at the discussion thread again. You can bundle just the virtual camera drivers of OBS, instead of all of OBS. Even though this is not an official method, it works.

**Comment by Ajju2211** [comment]
Yeah, I will check that out
